### PR TITLE
#8 different approach

### PR DESCRIPTION
**Pull request by Mulchman**
I really liked the simplicity of @michael-donat 's server process but unfortunately the hosting is limited. I can't run a node process (and I don't have root) so that leaves us with other server-side things to try.

This PR adds `scrape.php` at `http://api.destinyraidstatus.com/the100` which parses a 100.io game page and returns the players as JSON.

I haven't done PHP since the 90s so any input is greatly appreciated.

### CODE REVIEW

**Comment by Mulchman** [comment]
It could really use some error checking in the .php file, as well as squelching errors being written to a local log file that I'll inevitably forget about until it eats up all the disk space.

**Comment by Mulchman** [comment]
Found a game where a guy has both an XBL gamertag and PSN Id showing: https://www.the100.io/game/969425

> XBL: LiterallyGinger PSN: Moist_Ginger 

I imagine this could be a common thing for players that play both platforms, @michael-donat ?

**Comment by michael-donat** [comment]
We can change the php script to return both with indication of platform, and let the front end filter according to DRS platform switch.

Or maybe better to make the api accept platform and do the filtering server side.

Can you link me a game like this?

**Comment by Mulchman** [comment]
You may not be caught up on the other comments- the PHP script is pulling all the players and the platform. (I don't want the platform choice to be on the Angular/front-end/client side; it causes more dependencies and is error prone.) A sample game where a player has both an Xbox and PlayStation name listed is here: https://www.the100.io/game/969425

**Pull request merged**
